# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: False

# Setup
title:               My blog
tagline:             hello - World, I'm here
description:         '같이의 가치를 믿으며, <br> 매일 무엇인가를 배우고 싶은 사람입니다.'
url:                 
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Lee Gyumin
  url:               https://gyuminjack.github.com
  email:             sld9849@gmail.com

# Custom vars
version:             1.0.0
plugins: [jekyll-paginate]

category_dir: category/
tag_dir: tag/

excerpt_separator: ""